[package]
name = "WasmbotTest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"] # cdylib for wasm; lib for native

[profile.release]
strip = true
lto = true

[dependencies]
wasmbot_client = { git = "https://github.com/sjml/wasmbots.git", version = "0.0.0", branch = "next" }
